version: "3"
services:
  emby:
    image: linuxserver/emby
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Argentina/Mendoza
      - UMASK_SET=022 #optional
    volumes:
      - /media/usb/movies:/data/usb-movies
      - /home/pi/ShareFile:/data/net-movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
    restart: always